name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install
      working-directory: 2024-2/Semana1/Actividad1-Introduccion/devops-practice

    - name: Build and run Docker Compose
      run: |
        docker-compose up --build -d
      working-directory: 2024-2/Semana1/Actividad1-Introduccion/devops-practice

    - name: Run tests
      run: docker exec devops-practice-container npm test

    - name: Stop and clean Docker Compose
      run: |
        docker-compose down
      working-directory: 2024-2/Semana1/Actividad1-Introduccion/devops-practice

    # Original commands, now commented out
    # - name: Build Docker image
    #   run: docker build -t devops-practice 2024-2/Semana1/Actividad1-Introduccion/devops-practice/.

    # - name: Run tests
    #   run: npm test
    #   working-directory: 2024-2/Semana1/Actividad1-Introduccion/devops-practice

    # - name: Run Docker container
    #   run: docker run -d -p 3001:3001 devops-practice
